import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Helmet } from "react-helmet-async";
import { useNavigate } from "react-router-dom";

export default function TermsOfService() {
  const navigate = useNavigate();

  const pageTitle = "Terms of Service - CourseCraft";
  const pageDescription =
    "These Terms of Service govern your use of CourseCraft. Learn about user responsibilities, acceptable use, and our limitations of liability.";

  return (
    <div className="mobile-layout">
      <div className="mobile-content">
        <Helmet>
          <title>{pageTitle}</title>
          <meta name="description" content={pageDescription} />
          <meta
            name="keywords"
            content="create course, custom learning, AI education, YouTube learning"
          />
          <link rel="canonical" href="https://course-craft.tech/terms" />

          {/* Open Graph / Facebook */}
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://course-craft.tech/terms" />
          <meta property="og:title" content={pageTitle} />
          <meta property="og:description" content={pageDescription} />

          {/* Twitter */}
          <meta
            property="twitter:url"
            content="https://course-craft.tech/terms"
          />
          <meta property="twitter:title" content={pageTitle} />
          <meta property="twitter:description" content={pageDescription} />
        </Helmet>
        <div className="max-w-3xl mx-auto px-8 py-8">
          <div className="flex items-center mb-6">
            <Button
              variant="link"
              size="sm"
              className="mr-2"
              onClick={() => navigate(-1)}
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-200">
              Terms of Service
            </h1>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="text-slate-600 dark:text-slate-400">
              Last updated: April 28, 2025
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Acceptance of Terms
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              By accessing or using CourseCraft ("we", "our", "us", or "the
              Service"), you agree to be bound by these Terms of Service and our
              Privacy Policy. If you do not agree to these terms, you must not
              use our Service.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Use of the Service
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              You may use CourseCraft solely for personal, non-commercial
              educational purposes. You must not use the Service for any illegal
              or unauthorized purpose, including violating any intellectual
              property rights of others or uploading content that you do not
              have permission to use.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              User Accounts
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              To access certain features, you must create an account using your
              email address via Supabase authentication. You are responsible for
              maintaining the confidentiality of your login information and for
              all activities that occur under your account.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Intellectual Property
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              CourseCraft and its original content, features, and functionality
              are and will remain the exclusive property of CourseCraft and its
              licensors. You may not copy, modify, distribute, sell, or lease
              any part of our Service without our prior written consent.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Third-Party Content
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              Our Service uses third-party APIs, including OpenAI and YouTube
              Data API, to generate and display course content. We are not
              responsible for the accuracy, legality, or appropriateness of
              third-party content retrieved or generated by these services.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Termination
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              We may suspend or terminate your access to the Service at any time
              without notice if you violate these Terms. Upon termination, your
              right to use the Service will immediately cease.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Disclaimer of Warranties
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              The Service is provided on an "as-is" and "as-available" basis. We
              disclaim all warranties, express or implied, including
              merchantability, fitness for a particular purpose, and
              non-infringement.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Limitation of Liability
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              To the maximum extent permitted by law, CourseCraft and its
              affiliates shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages arising out of your
              use of the Service.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Governing Law
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              These Terms are governed by and construed in accordance with the
              laws of the State of Missouri, United States, without regard to
              its conflict of law principles.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Changes to Terms
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              We may update these Terms of Service from time to time. Changes
              will be posted on this page with a revised "Last updated" date.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-800 dark:text-slate-200">
              Contact Us
            </h2>
            <p className="text-slate-600 dark:text-slate-400">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="text-slate-600 dark:text-slate-400 mt-2">
              <strong>Email:</strong> support@course-craft.tech
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
